backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/images"
  
collections:
  - name: "Posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Author Profile", name: "author_profile", widget: "boolean"}
      - {label: "Entries Layout", name: "entries_layout", widget: "string"}
      - {label: "Collection", name: "collection", widget: "string"}
      - {label: "Header", name: "header", widget: "object"}
      - {label: "Sidebar", name: "sidebar", widget: "object"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Classes", name: "classes", widget: "list"}
      - {label: "Canonical Url", name: "canonical_url", widget: "string"}
      - {label: "Toc", name: "toc", widget: "boolean"}
      - {label: "Toc Label", name: "toc_label", widget: "string"}
      - {label: "Toc Icon", name: "toc_icon", widget: "string"}
      - {label: "Taxonomy", name: "taxonomy", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Author Profile", name: "author_profile", widget: "boolean"}
      - {label: "Entries Layout", name: "entries_layout", widget: "string"}
      - {label: "Collection", name: "collection", widget: "string"}
      - {label: "Header", name: "header", widget: "object"}
      - {label: "Sidebar", name: "sidebar", widget: "object"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Classes", name: "classes", widget: "list"}
      - {label: "Canonical Url", name: "canonical_url", widget: "string"}
      - {label: "Toc", name: "toc", widget: "boolean"}
      - {label: "Toc Label", name: "toc_label", widget: "string"}
      - {label: "Toc Icon", name: "toc_icon", widget: "string"}
      - {label: "Taxonomy", name: "taxonomy", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}